Gam6itko\Cbrf\Model\CreditOrgInfo:
    xml_root_name: CreditOrgInfo
    properties:
        co:
            expose: true
            access_type: public_method
            serialized_name: CO
            accessor:
                getter: getCO
                setter: setCO
            xml_list:
                inline: true
                entry_name: CO
            type: array<Gam6itko\Cbrf\Model\CreditOrgInfo\COAType>
        lic:
            expose: true
            access_type: public_method
            serialized_name: LIC
            accessor:
                getter: getLIC
                setter: setLIC
            xml_list:
                inline: true
                entry_name: LIC
            type: array<Gam6itko\Cbrf\Model\CreditOrgInfo\LICAType>
