Gam6itko\Cbrf\Model\CreditOrg\EnumCreditsAType:
    properties:
        intCode:
            expose: true
            access_type: public_method
            serialized_name: IntCode
            accessor:
                getter: getIntCode
                setter: setIntCode
            type: float
        orgName:
            expose: true
            access_type: public_method
            serialized_name: OrgName
            accessor:
                getter: getOrgName
                setter: setOrgName
            type: string
        bic:
            expose: true
            access_type: public_method
            serialized_name: bic
            accessor:
                getter: getBic
                setter: setBic
            type: string
        regNumber:
            expose: true
            access_type: public_method
            serialized_name: cregnum
            accessor:
                getter: getRegNumber
                setter: setRegNumber
            type: int
