Gam6itko\Cbrf\Model\EnumBIC\BICAType:
    properties:
        bic:
            expose: true
            access_type: public_method
            serialized_name: BIC
            accessor:
                getter: getBIC
                setter: setBIC
            type: string
        rc:
            expose: true
            access_type: public_method
            serialized_name: RC
            accessor:
                getter: getRC
                setter: setRC
            type: DateTime
        nm:
            expose: true
            access_type: public_method
            serialized_name: NM
            accessor:
                getter: getNM
                setter: setNM
            type: string
        rb:
            expose: true
            access_type: public_method
            serialized_name: RB
            accessor:
                getter: getRB
                setter: setRB
            type: string
        rn:
            expose: true
            access_type: public_method
            serialized_name: RN
            accessor:
                getter: getRN
                setter: setRN
            type: float
        intCode:
            expose: true
            access_type: public_method
            serialized_name: intCode
            accessor:
                getter: getIntCode
                setter: setIntCode
            type: float
