Gam6itko\Cbrf\Model\EnumBIC:
    xml_root_name: EnumBIC
    properties:
        bic:
            expose: true
            access_type: public_method
            serialized_name: BIC
            accessor:
                getter: getBIC
                setter: setBIC
            xml_list:
                inline: true
                entry_name: BIC
            type: array<Gam6itko\Cbrf\Model\EnumBIC\BICAType>
