Gam6itko\Cbrf\Model\F101DATA\FDAType:
    properties:
        dt:
            expose: true
            access_type: public_method
            serialized_name: DT
            accessor:
                getter: getDT
                setter: setDT
            type: DateTime
        val:
            expose: true
            access_type: public_method
            serialized_name: val
            accessor:
                getter: getVal
                setter: setVal
            type: float
        ap:
            expose: true
            access_type: public_method
            serialized_name: AP
            accessor:
                getter: getAP
                setter: setAP
            type: string
