Gam6itko\Cbrf\Model\F101DATA\FDFAType:
    properties:
        dt:
            expose: true
            access_type: public_method
            serialized_name: dt
            accessor:
                getter: getDt
                setter: setDt
            type: DateTime
        plan:
            expose: true
            access_type: public_method
            serialized_name: pln
            accessor:
                getter: getPlan
                setter: setPlan
            type: string
        ap:
            expose: true
            access_type: public_method
            serialized_name: ap
            accessor:
                getter: getAp
                setter: setAp
            type: int
        inRur:
            expose: true
            access_type: public_method
            serialized_name: vr
            accessor:
                getter: getInRur
                setter: setInRur
            type: float
        inCur:
            expose: true
            access_type: public_method
            serialized_name: vv
            accessor:
                getter: getInCur
                setter: setInCur
            type: float
        inTotal:
            expose: true
            access_type: public_method
            serialized_name: vitg
            accessor:
                getter: getInTotal
                setter: setInTotal
            type: float
        sumDebitRur:
            expose: true
            access_type: public_method
            serialized_name: ora
            accessor:
                getter: getSumDebitRur
                setter: setSumDebitRur
            type: float
        sumDebitCur:
            expose: true
            access_type: public_method
            serialized_name: ova
            accessor:
                getter: getSumDebitCur
                setter: setSumDebitCur
            type: float
        sumDebitTotal:
            expose: true
            access_type: public_method
            serialized_name: oitga
            accessor:
                getter: getSumDebitTotal
                setter: setSumDebitTotal
            type: float
        sumCreditRur:
            expose: true
            access_type: public_method
            serialized_name: orp
            accessor:
                getter: getSumCreditRur
                setter: setSumCreditRur
            type: float
        sumCreditCur:
            expose: true
            access_type: public_method
            serialized_name: ovp
            accessor:
                getter: getSumCreditCur
                setter: setSumCreditCur
            type: float
        sumCreditTotal:
            expose: true
            access_type: public_method
            serialized_name: oitgp
            accessor:
                getter: getSumCreditTotal
                setter: setSumCreditTotal
            type: float
        outRur:
            expose: true
            access_type: public_method
            serialized_name: ir
            accessor:
                getter: getOutRur
                setter: setOutRur
            type: float
        outCur:
            expose: true
            access_type: public_method
            serialized_name: iv
            accessor:
                getter: getOutCur
                setter: setOutCur
            type: float
        outTotal:
            expose: true
            access_type: public_method
            serialized_name: iitg
            accessor:
                getter: getOutTotal
                setter: setOutTotal
            type: float
