Gam6itko\Cbrf\Model\F101DATA:
    xml_root_name: F101DATA
    properties:
        fd:
            expose: true
            access_type: public_method
            serialized_name: FD
            accessor:
                getter: getFD
                setter: setFD
            xml_list:
                inline: true
                entry_name: FD
            type: array<Gam6itko\Cbrf\Model\F101DATA\FDAType>
        fdf:
            expose: true
            access_type: public_method
            serialized_name: FDF
            accessor:
                getter: getFDF
                setter: setFDF
            xml_list:
                inline: true
                entry_name: FDF
            type: array<Gam6itko\Cbrf\Model\F101DATA\FDFAType>
