Gam6itko\Cbrf\Model\F102DATAFULL:
    xml_root_name: F102DATAFULL
    properties:
        fdf:
            expose: true
            access_type: public_method
            serialized_name: FDF
            accessor:
                getter: getFDF
                setter: setFDF
            xml_list:
                inline: true
                entry_name: FDF
            type: array<Gam6itko\Cbrf\Model\F102DATAFULL\FDFAType>
