Gam6itko\Cbrf\Model\F102DATAFULL\FDFAType:
    properties:
        dt:
            expose: true
            access_type: public_method
            serialized_name: DT
            accessor:
                getter: getDT
                setter: setDT
            type: DateTime
        val:
            expose: true
            access_type: public_method
            serialized_name: val
            accessor:
                getter: getVal
                setter: setVal
            type: float
        r:
            expose: true
            access_type: public_method
            serialized_name: r
            accessor:
                getter: getR
                setter: setR
            type: float
        v:
            expose: true
            access_type: public_method
            serialized_name: v
            accessor:
                getter: getV
                setter: setV
            type: float
