Gam6itko\Cbrf\Model\F123DATA\F123AType:
    properties:
        code:
            expose: true
            access_type: public_method
            serialized_name: CODE
            accessor:
                getter: getCode
                setter: setCode
            type: string
        name:
            expose: true
            access_type: public_method
            serialized_name: NAME
            accessor:
                getter: getName
                setter: setName
            type: string
        value:
            expose: true
            access_type: public_method
            serialized_name: VALUE
            accessor:
                getter: getValue
                setter: setValue
            type: float
