Gam6itko\Cbrf\Model\F123DATA:
    xml_root_name: F123DATA
    properties:
        f123:
            expose: true
            access_type: public_method
            serialized_name: F123
            accessor:
                getter: getF123
                setter: setF123
            xml_list:
                inline: true
                entry_name: F123
            type: array<Gam6itko\Cbrf\Model\F123DATA\F123AType>
