Gam6itko\Cbrf\Model\F134DATA\FDAType:
    properties:
        ns:
            expose: true
            access_type: public_method
            serialized_name: NS
            accessor:
                getter: getNS
                setter: setNS
            type: string
        pn:
            expose: true
            access_type: public_method
            serialized_name: PN
            accessor:
                getter: getPN
                setter: setPN
            type: string
        value:
            expose: true
            access_type: public_method
            serialized_name: VAL
            accessor:
                getter: getValue
                setter: setValue
            type: float
