Gam6itko\Cbrf\Model\F134DATA\FDAType:
    properties:
        nS:
            expose: true
            access_type: public_method
            serialized_name: NS
            accessor:
                getter: getNS
                setter: setNS
            type: string
        pN:
            expose: true
            access_type: public_method
            serialized_name: PN
            accessor:
                getter: getPN
                setter: setPN
            type: string
        vAL:
            expose: true
            access_type: public_method
            serialized_name: VAL
            accessor:
                getter: getVAL
                setter: setVAL
            type: float
