Gam6itko\Cbrf\Model\F134DATA:
    xml_root_name: F134DATA
    properties:
        fd:
            expose: true
            access_type: public_method
            serialized_name: FD
            accessor:
                getter: getFD
                setter: setFD
            xml_list:
                inline: true
                entry_name: FD
            type: array<Gam6itko\Cbrf\Model\F134DATA\FDAType>
