Gam6itko\Cbrf\Model\F135DATA\F1355AType:
    properties:
        dt:
            expose: true
            access_type: public_method
            serialized_name: DT
            accessor:
                getter: getDT
                setter: setDT
            type: DateTime
