Gam6itko\Cbrf\Model\F135DATA:
    xml_root_name: F135DATA
    properties:
        f1351:
            expose: true
            access_type: public_method
            serialized_name: F135_1
            accessor:
                getter: getF1351
                setter: setF1351
            xml_list:
                inline: true
                entry_name: F135_1
            type: array<Gam6itko\Cbrf\Model\F135DATA\F1351AType>
        f1352:
            expose: true
            access_type: public_method
            serialized_name: F135_2
            accessor:
                getter: getF1352
                setter: setF1352
            xml_list:
                inline: true
                entry_name: F135_2
            type: array<Gam6itko\Cbrf\Model\F135DATA\F1352AType>
        f1353:
            expose: true
            access_type: public_method
            serialized_name: F135_3
            accessor:
                getter: getF1353
                setter: setF1353
            xml_list:
                inline: true
                entry_name: F135_3
            type: array<Gam6itko\Cbrf\Model\F135DATA\F1353AType>
        f1354:
            expose: true
            access_type: public_method
            serialized_name: F135_4
            accessor:
                getter: getF1354
                setter: setF1354
            xml_list:
                inline: true
                entry_name: F135_4
            type: array<Gam6itko\Cbrf\Model\F135DATA\F1354AType>
        f1355:
            expose: true
            access_type: public_method
            serialized_name: F135_5
            accessor:
                getter: getF1355
                setter: setF1355
            xml_list:
                inline: true
                entry_name: F135_5
            type: array<Gam6itko\Cbrf\Model\F135DATA\F1355AType>
        f1356:
            expose: true
            access_type: public_method
            serialized_name: F135_6
            accessor:
                getter: getF1356
                setter: setF1356
            xml_list:
                inline: true
                entry_name: F135_6
            type: array<Gam6itko\Cbrf\Model\F135DATA\F1356AType>
