Gam6itko\Cbrf\Model\F135DATA\F1354AType:
    properties:
        num:
            expose: true
            access_type: public_method
            serialized_name: num
            accessor:
                getter: getNum
                setter: setNum
            type: int
        nn:
            expose: true
            access_type: public_method
            serialized_name: nn
            accessor:
                getter: getNn
                setter: setNn
            type: string
        nnd:
            expose: true
            access_type: public_method
            serialized_name: nnd
            accessor:
                getter: getNnd
                setter: setNnd
            type: float
        dt:
            expose: true
            access_type: public_method
            serialized_name: DT
            accessor:
                getter: getDT
                setter: setDT
            type: DateTime
