Gam6itko\Cbrf\Model\IndicatorsEnum101:
    xml_root_name: IndicatorsEnum101
    properties:
        eIND:
            expose: true
            access_type: public_method
            serialized_name: EIND
            accessor:
                getter: getEIND
                setter: setEIND
            xml_list:
                inline: true
                entry_name: EIND
            type: array<Gam6itko\Cbrf\Model\IndicatorsEnum101\EINDAType>
